version: '3'

services:
  quicklygabbing-laravel-laravel-blog-init:
    image: quicklygabbing-laravel-blog-init
    build:
      context: .
      dockerfile: php7.2.Dockerfile
    volumes:
      - ./www:/home/quicklygabbing/www
      - ./scrypt/laravel.sh:/init.sh
    command: "/init.sh"
  quicklygabbing-laravel-lumen-blog-init:
    image: quicklygabbing-laravel-blog-init
    build:
      context: .
      dockerfile: php7.2.Dockerfile
    volumes:
      - ./www:/home/quicklygabbing/www
      - ./scrypt/lumen.sh:/init.sh
    command: "/init.sh"
