version: '3'

services:
  quicklygabbing-laravel-blog-init:
    image: quicklygabbing-laravel-blog-init
    build:
      context: .
      dockerfile: php7.2.Dockerfile
    volumes:
      - ./www:/home/quicklygabbing/www
      - ./scrypt/init.sh:/init.sh
    command: "/init.sh"
#    command: "rm -rf *; composer create-project --prefer-dist laravel/laravel blogOD"
